export const restaurantList = [
    {
      vendorId: "1112",
      vendorName: "Sharma Ji",
      businessName: "Sharma Ji Restaurant",
      businessCoverImage: "https://sukhis.com/app/uploads/2018/10/ex2.jpg",
      PhoneNumber: 982135432,
      zipcode: 412541,
      emailId: "sharmaji@gmail.com",
      vendorRating: 4.5,
      numberOfOrderedPlaced: 350,
      subCategoryId: "North Indian",
      subCategoryId: "Fast food",
      product: [
        {
          productId: "2223",
          productName: "Dosa",
          subCategoryId: "North Indian",
          vendorId: "1112",
          productPrice: "125",
          productRating: "2.5",
          productDescription: "Indian Dosa",
          productPhoto: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
          productSubDescription: "Medium size dosa",
          isVeg: false,
          
        },
        {
          productId: "2224",
          productName: "burger",
          subCategoryId: "Snacks",
          vendorId: "1112",
          productPrice: "120",
          productRating: "4.5",
          productDescription: "Indian burger",
          productPhoto: "https://www.thespruceeats.com/thmb/ad4-cZdHW0fHWDn_JSuh3FTjLag=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/garlic-burger-patties-333503-hero-01-e4df660ff27b4e5194fdff6d703a4f83.jpg",
          productSubDescription: "Medium size burger",    
          isVeg: false,      
        },
        {
          productId: "2225",
          productName: "samosa",
          subCategoryId: "fast food",
          vendorId: "1112",
          productPrice: "50",
          productRating: "3.5",
          productDescription: "Indian Fast Food",
          productPhoto: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Samosachutney.jpg",
          productSubDescription: "large size samosa",   
          isVeg: false,       
        },
      ],
    },
    {
      vendorId: "1113",
      vendorName: "Pandya Ji",
      businessName: "Pandya Restaurant",
      businessCoverImage: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
      PhoneNumber: 982135432,
      zipcode: 412541,
      emailId: "Pandya@gmail.com",
      vendorRating: 3,
      numberOfOrderedPlaced: 250,
      subCategoryId: "South food",      
      product: [
        {
          productId: "3223",
          productName: "idli",
          subCategoryId: "South Indian",
          vendorId: "1113",
          productPrice: "125",
          productRating: "4.5",
          productDescription: "Indian Idli",
          productPhoto: "https://shwetainthekitchen.com/wp-content/uploads/2022/01/Idli.jpg",
          productSubDescription: "Medium size idli",
          isVeg: false,
          
        },
        {
          productId: "3224",
          productName: "burger",
          subCategoryId: "Snacks",
          vendorId: "1113",
          productPrice: "100",
          productRating: "2.5",
          productDescription: "Indian burger",
          productPhoto: "https://www.seriouseats.com/thmb/vOsRuVEH7ZhQVOVVP42VJ-eu4Rg=/880x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/20210607-INNOUTBURGERS-JANJIGIAN-seriouseats-23-b2b8a505ff414272aab71590a8985b85.jpg",
          productSubDescription: "Medium size burger",    
          isVeg: true,      
        },
        {
          productId: "3225",
          productName: "samosa",
          subCategoryId: "fast food",
          vendorId: "1113",
          productPrice: "53",
          productRating: "4.5",
          productDescription: "Indian Fast Food",
          productPhoto: "https://sukhis.com/app/uploads/2018/10/ex2.jpg",
          productSubDescription: "large size samosa", 
          isVeg: true,         
        },
      ],
    },
    {
      vendorId: "1114",
      vendorName: "Mishra Ji",
      businessName: "Mishra Restaurant",
      businessCoverImage: "https://shwetainthekitchen.com/wp-content/uploads/2022/01/Idli.jpg",
      PhoneNumber: 982135432,
      zipcode: 456123,
      emailId: "MishraJi@gmail.com",
      vendorRating: 2.5,
      numberOfOrderedPlaced: 250,
      subCategoryId: "South Indian",
      product: [
        {
          productId: "4223",
          productName: "idli",
          subCategoryId: "South Indian",
          vendorId: "1114",
          productPrice: "115",
          productRating: "2.5",
          productDescription: "Indian Idli",
          productPhoto: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/idli.jpg.webp",
          productSubDescription: "Medium size idli",
          isVeg: false,
        },
        {
          productId: "4224",
          productName: "burger",
          subCategoryId: "Snacks",
          vendorId: "1114",
          productPrice: "100",
          productRating: "2.5",
          productDescription: "Indian burger",
          productPhoto: "https://assets.epicurious.com/photos/5c745a108918ee7ab68daf79/1:1/w_1920,c_limit/Smashburger-recipe-120219.jpg",
          productSubDescription: "Medium size burger",  
          isVeg: false,        
        },
        {
          productId: "4225",
          productName: "samosa",
          subCategoryId: "fast food",
          vendorId: "1114",
          productPrice: "42",
          productRating: "4.5",
          productDescription: "Indian Fast Food",
          productPhoto: "https://i0.wp.com/vegecravings.com/wp-content/uploads/2017/03/samosa-recipe-step-by-step-instructions.jpg?resize=1024%2C976&quality=65&strip=all&ssl=1",
          productSubDescription: "large size samosa",   
          isVeg: false,       
        },
      ],
    },
    {
      vendorId: "1115",
      vendorName: "ratan Sharma",
      businessName: "Food Lover",
      businessCoverImage: "https://www.thespruceeats.com/thmb/ad4-cZdHW0fHWDn_JSuh3FTjLag=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/garlic-burger-patties-333503-hero-01-e4df660ff27b4e5194fdff6d703a4f83.jpg",
      PhoneNumber: 982135432,
      zipcode: 412333,
      emailId: "foodlover@gmail.com",
      vendorRating: 3.5,
      numberOfOrderedPlaced: 250,
      subCategoryId: "Fast food",      
      product:[],
    },
    {
      vendorId: "1116",
      vendorName: "Roy Ji",
      businessName: "Fresh Food Restaurant",
      businessCoverImage: "https://lh3.googleusercontent.com/eDknPUTcea-07etrh_INv8LV5Zp97McLtu97JUkFaHB-Y6LsC7FACPXaz7lISt02WGNQ4dlQiwjHOOIVwxdyVgiiqol9lcEYZHBNJow",
      PhoneNumber: 9821585432,
      zipcode: 410541,
      emailId: "freshFood@gmail.com",
      vendorRating: 4.3,
      numberOfOrderedPlaced: 750,
      subCategoryId: "Regular Thali",      
      product:[],
    },
    {
      vendorId: "1117",
      vendorName: "Spicy",
      businessName: "Spicy Restaurant",
      businessCoverImage: "https://www.simplyrecipes.com/thmb/YR4CZyRSLKCFCLkU50UEfgpkG9w=/648x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__06__Spicy-Fried-Chicken-LEAD-3-24b25010ba0c4737b5fa5957f8f22d0e.jpg",
      PhoneNumber: 9821585432,
      zipcode: 410641,
      emailId: "Spicy@gmail.com",
      vendorRating: 4.1,
      numberOfOrderedPlaced: 50,
      subCategoryId: "Spicy Chicken",      
      product:[],
    },
    {
      vendorId: "1117",
      vendorName: "Saurab Roy",
      businessName: "AFC",
      businessCoverImage: "https://afc.world/wp-content/uploads/2021/10/AFC-Bucket-Mob.png",
      PhoneNumber: 9821585432,
      zipcode: 410541,
      emailId: "saurabroy@gmail.com",
      vendorRating: 4.3,
      numberOfOrderedPlaced: 450,
      subCategoryId: "Fried Chicken",     
      product:[],
    },
    {
      vendorId: "1118",
      vendorName: "Rohit Roy",
      businessName: "Tuli's Restaurant",
      businessCoverImage: "https://www.nehascookbook.com/wp-content/uploads/2021/08/Punjabi-thali-WS.jpg",
      PhoneNumber: 9821585432,
      zipcode: 410541,
      emailId: "tulis@gmail.com",
      vendorRating: 4.3,
      numberOfOrderedPlaced: 450,
      subCategoryId: "Indian Dish",      
      product:[],
    },
  ];