export const restaurantList = [
  {
    vendorId: "1112",
    vendorName: "Sharma Ji",
    businessName: "Sharma Ji Resturant",
    businessAddress: "Toronto",
    vendorProfileImage:
      "https://nationaltoday.com/wp-content/uploads/2021/07/shutterstock_1518533924-min.jpg",
    businessCoverImage: "https://sukhis.com/app/uploads/2018/10/ex2.jpg",
    phoneNumber: 9876541112,
    zipcode: 80112,
    emailId: "SharmaJi@gmail.com",
    vendorRating: 4,
    numberOfOrderedPlaced:102,
    subCategoryId: "South Indian",
    dietry: "Veg",
    tag: "Newly Added",
    foodSafetyCertified: "Yes",
    reviews: "53",    
    product: [
      {
        productId: "2225",
        productName: "Rabri 2",
        subCategoryId: "Gujrati",
        vendorId: "1112",
        productPrice: "20",
        productRating: "4",
        productDescription: "Gujrati flavored dish etc etc",
        productPhoto:
          "https://1.bp.blogspot.com/-3C1V-GCx88Y/X2GrcU_4TaI/AAAAAAABEE4/brvxMKihnT0Cfln9Q_gwrbswepg6pR0RgCLcBGAsYHQ/s1600/rabdi-recipe.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2223",
        productName: "Butter Naan 1",
        subCategoryId: "South Indian",
        vendorId: "1112",
        productPrice: "24",
        productRating: "3",
        productDescription: "South Indian flavored dish etc etc",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2224",
        productName: "Chowemin 4",
        subCategoryId: "South Indian",
        vendorId: "1112",
        productPrice: "11",
        productRating: "2",
        productDescription: "South Indian flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHJxJQ1-eMNrrWpINfzq0NQdwCJGkBNztEERrGUS0i_-r0GUWFvihmiT0gRYn6rotDTsA&usqp=CAU",
        productSubDescription: "",
        isVeg: "true",
      },
    ],
  },
  {
    vendorId: "1113",
    vendorName: "Pandya Ji",
    businessName: "Pandya Ji Resturant",
    businessAddress: "Kitchener",
    vendorProfileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQitUZUZUafH4yVj15BC8wTrf7ohw8dO5jjSa4RaA5JEEpGfET-pTfZ-zEGDWYFTegXCoI&usqp=CAU",
    businessCoverImage:
      "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
    phoneNumber: 9876541113,
    zipcode: 80113,
    emailId: "PandyaJi@gmail.com",
    vendorRating: 4,
    numberOfOrderedPlaced:151,
    subCategoryId: "0",
    dietry: "Non Veg",
    tag: "Trending",
    foodSafetyCertified: "No",
    reviews: "95",
    subCategoryId: "South food",
    product: [
      {
        productId: "2227",
        productName: "Chilli Paneer 3",
        subCategoryId: "West Indian",
        vendorId: "1113",
        productPrice: "22",
        productRating: "1",
        productDescription: "West Indian flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmUAYKaMxyV1TQleaRJriiJJ4Iyo5VPANOAZmRpx2qdrwhK9Jg7Vo88NrdilyObj5AO1c&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2229",
        productName: "Dum Aloo 4",
        subCategoryId: "Chinese",
        vendorId: "1113",
        productPrice: "25",
        productRating: "5",
        productDescription: "Chinese flavored dish etc etc",
        productPhoto:
          "https://indianpakwan.com/wp-content/uploads/2020/12/kashmiri-dum-aloo-1200x675.webp",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2228",
        productName: "Idli 3",
        subCategoryId: "East Indian",
        vendorId: "1113",
        productPrice: "12",
        productRating: "3",
        productDescription: "East Indian flavored dish etc etc",
        productPhoto:
          "https://artofpalate.com/wp-content/uploads/2016/08/idli-with-rice-flour.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2226",
        productName: "Manchurian 4",
        subCategoryId: "Bengali",
        vendorId: "1113",
        productPrice: "25",
        productRating: "1",
        productDescription: "Bengali flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8jburSwC-lUCRMmCionODgcELAZk-7uBqdtWrGJ58Uz-p8Lu87jtTvJe_qugMo9jZYnc&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2230",
        productName: "Sambhar 3",
        subCategoryId: "Batter",
        vendorId: "1113",
        productPrice: "20",
        productRating: "4",
        productDescription: "Batter flavored dish etc etc",
        productPhoto:
          "https://www.cookclickndevour.com/wp-content/uploads/2015/07/sambar-recipe.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
    ],
  },
  {
    vendorId: "1114",
    vendorName: "Mishra Ji",
    businessName: "Mishra Ji Resturant",
    businessAddress: "Brampton",
    vendorProfileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx7vffX899ZdsXO7rybaRBFzVeIgKLBnzfUu7xlcj0bER3_UBuBlzrzygvlkR-mLUV5GM&usqp=CAU",
    businessCoverImage:
      "https://shwetainthekitchen.com/wp-content/uploads/2022/01/Idli.jpg",
    phoneNumber: 9876541114,
    zipcode: 80114,
    emailId: "MishraJi@gmail.com",
    vendorRating: 5,
    numberOfOrderedPlaced:46,
    subCategoryId: "Sweets",
    dietry: "Vegan",
    tag: "Newly Added",
    foodSafetyCertified: "Yes",
    reviews: "105",
    subCategoryId: "South Indian",
    product: [
      {
        productId: "2233",
        productName: "Kadai Paneer 2",
        subCategoryId: "Dessert",
        vendorId: "1114",
        productPrice: "10",
        productRating: "1",
        productDescription: "Dessert flavored dish etc etc",
        productPhoto:
          "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/04/kadai-paneer-recipe.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2232",
        productName: "Dosa 4",
        subCategoryId: "Bakery",
        vendorId: "1114",
        productPrice: "17",
        productRating: "1",
        productDescription: "Bakery flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJagxVIY9vknYngM1fWQCO3yXk3xEWKtEPlA1bDhWcLOyYhR22QI_H723iDFBbQ4e65SU&usqp=CAU",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2236",
        productName: "Gulab Jamun 2",
        subCategoryId: "North Indian",
        vendorId: "1114",
        productPrice: "20",
        productRating: "4",
        productDescription: "North Indian flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_0ZsZniyT4zTlh6dOTeUMfJhFmZPQbp1T7K-1K44wumTZwD8VNKI2kYEbY92219RRGDA&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2231",
        productName: "Flavored Cake 1",
        subCategoryId: "Sweets",
        vendorId: "1114",
        productPrice: "20",
        productRating: "4",
        productDescription: "Sweets flavored dish etc etc",
        productPhoto:
          "https://preppykitchen.com/wp-content/uploads/2019/06/Chocolate-cake-recipe-1200a.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2234",
        productName: "Gulab Jamun 3",
        subCategoryId: "Thali",
        vendorId: "1114",
        productPrice: "16",
        productRating: "5",
        productDescription: "Thali flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCx7p1fOOP5v_WgidDO_kF7jxFerYDCvFyJNpnTQ-NYgzVwz8NQqe2heMaNEmiwVPvbjk&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2235",
        productName: "Idli 3",
        subCategoryId: "Catering",
        vendorId: "1114",
        productPrice: "19",
        productRating: "3",
        productDescription: "Catering flavored dish etc etc",
        productPhoto:
          "https://artofpalate.com/wp-content/uploads/2016/08/idli-with-rice-flour.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2242",
        productName: "Saag 2",
        subCategoryId: "Chinese",
        vendorId: "1115",
        productPrice: "14",
        productRating: "3",
        productDescription: "Chinese flavored dish etc etc",
        productPhoto:
          "https://www.cookingcarnival.com/wp-content/uploads/2015/05/Rava-Dosa-2.jpg",
        productSubDescription: "",
        isVeg: "true",
      },
    ],
  },
  {
    vendorId: "1115",
    vendorName: "Punjabi Chef",
    businessName: "Punjabi Chef Resturant",
    businessAddress: "Brampton",
    vendorProfileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9-i8uAwxXWsgxMNWzEQGgArx5tcCAlotSoLuD7dZiN349-8SGhbsbLwhUDEh2vElK3WA&usqp=CAU",
    businessCoverImage:
      "https://www.thespruceeats.com/thmb/ad4-cZdHW0fHWDn_JSuh3FTjLag=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/garlic-burger-patties-333503-hero-01-e4df660ff27b4e5194fdff6d703a4f83.jpg",
    phoneNumber: 9876541115,
    zipcode: 80115,
    emailId: "PunjabiChef@gmail.com",
    vendorRating: 3,
    numberOfOrderedPlaced:221,
    subCategoryId: "South Indian",
    dietry: "Non Veg",
    tag: "Highly Ordered",
    foodSafetyCertified: "Yes",
    reviews: "125",
    subCategoryId: "Fast food",
    product: [
      {
        productId: "2239",
        productName: "Tandoor Naan 3",
        subCategoryId: "Bengali",
        vendorId: "1115",
        productPrice: "20",
        productRating: "3",
        productDescription: "Bengali flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtytSLRyW7_FR_hMaG9KmEDCbQsRLdsEBZ-Kb9RhDpg6j6xHWWdltTJoCyMDU-UOqhA4M&usqp=CAU",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2241",
        productName: "Momos 3",
        subCategoryId: "East Indian",
        vendorId: "1115",
        productPrice: "17",
        productRating: "2",
        productDescription: "East Indian flavored dish etc etc",
        productPhoto:
          "https://resize.indiatvnews.com/en/resize/oldbucket/715_-/lifestylelifestyle/IndiaTv94add1_momos-main-pic.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2243",
        productName: "Flavored Cake 2",
        subCategoryId: "Batter",
        vendorId: "1115",
        productPrice: "13",
        productRating: "1",
        productDescription: "Batter flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKlEuFGjA7u2DHC_TH3zEpUVit1ZCQitw53_U_PJijc56aORXFO6Iqv-DKjrrm6acJk18&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2238",
        productName: "Chilli Paneer 1",
        subCategoryId: "Gujrati",
        vendorId: "1115",
        productPrice: "11",
        productRating: "2",
        productDescription: "Gujrati flavored dish etc etc",
        productPhoto:
          "https://cdn.cookrepublic.com/wp-content/uploads/2021/09/chilli-paneer02.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2237",
        productName: "Veg Manchurian 3",
        subCategoryId: "South Indian",
        vendorId: "1115",
        productPrice: "13",
        productRating: "4",
        productDescription: "South Indian flavored dish etc etc",
        productPhoto:
          "https://mysticalindia.com.au/wp-content/uploads/2021/05/VEG-MUNCHURIAN.jpg",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2240",
        productName: "Rabri 4",
        subCategoryId: "West Indian",
        vendorId: "1115",
        productPrice: "16",
        productRating: "2",
        productDescription: "West Indian flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmymuNkU0lPwQWdiRlw1AIYV09GUL-VsPp4A&usqp=CAU",
        productSubDescription: "",
        isVeg: "true",
      },
    ],
  },
  {
    vendorId: "1116",
    vendorName: "Gujrati Tadka",
    businessName: "Gujrati Tadka Resturant",
    businessAddress: "Kitchener",
    vendorProfileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQurgaLdfQcVxCctSt7dyjseGKOpvFTtMLXJxuv4FjSyouc8-Y7-I4ogM_Ag6uPJNLHF0Y&usqp=CAU",
    businessCoverImage:
      "https://lh3.googleusercontent.com/eDknPUTcea-07etrh_INv8LV5Zp97McLtu97JUkFaHB-Y6LsC7FACPXaz7lISt02WGNQ4dlQiwjHOOIVwxdyVgiiqol9lcEYZHBNJow",
    phoneNumber: 9876541116,
    zipcode: 80116,
    emailId: "GujratiTadka@gmail.com",
    vendorRating: 4,
    numberOfOrderedPlaced:250,
    subCategoryId: "Bakery",
    dietry: "Non Veg",
    tag: "Newly Added",
    foodSafetyCertified: "No",
    reviews: "83",
    subCategoryId: "Regular Thali",
    product: [
      {
        productId: "2245",
        productName: "Daal Makhni 4",
        subCategoryId: "Bakery",
        vendorId: "1116",
        productPrice: "16",
        productRating: "4",
        productDescription: "Bakery flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHJxJQ1-eMNrrWpINfzq0NQdwCJGkBNztEERrGUS0i_-r0GUWFvihmiT0gRYn6rotDTsA&usqp=CAU",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2244",
        productName: "Chowemin 1",
        subCategoryId: "Sweets",
        vendorId: "1116",
        productPrice: "14",
        productRating: "5",
        productDescription: "Sweets flavored dish etc etc",
        productPhoto:
          "https://dinnerthendessert.com/wp-content/uploads/2020/07/Chicken-Chow-Mein-3.jpg",
        productSubDescription: "",
        isVeg: "true",
      },
    ],
  },
  {
    vendorId: "1117",
    vendorName: "Bengali Sweets",
    businessName: "Bengali Sweets Resturant",
    businessAddress: "Brampton",
    vendorProfileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUXTn2loFuNxF1MKrwI_oq_aM5kFUvLxbwZtd6ZmJj6vcJUTRuc2_OYDW-xe-763xht9E&usqp=CAU",
    businessCoverImage:
      "https://assets.cntraveller.in/photos/60eec8d39685bd2f77ff80c2/16:9/w_1024%2Cc_limit/masterchef-au-tandoori-chicken.jpg",
    phoneNumber: 9876541117,
    zipcode: 80117,
    emailId: "BengaliSweets@gmail.com",
    vendorRating: 3,
    numberOfOrderedPlaced:236,
    subCategoryId: "West Indian",
    dietry: "Vegan",
    tag: "Highly Ordered",
    foodSafetyCertified: "Yes",
    reviews: "120",
    subCategoryId: "Spicy Chicken",
    product: [
      {
        productId: "2246",
        productName: "Tandoor Naan 4",
        subCategoryId: "Dessert",
        vendorId: "1117",
        productPrice: "20",
        productRating: "1",
        productDescription: "Dessert flavored dish etc etc",
        productPhoto:
          "https://img-global.cpcdn.com/recipes/f4cc48403ca797ef/680x482cq70/tandoori-butter-naan-without-yeast-recipe-main-photo.jpg",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2247",
        productName: "Dhokla 5",
        subCategoryId: "Thali",
        vendorId: "1117",
        productPrice: "11",
        productRating: "1",
        productDescription: "Thali flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsy6i6JTcYwQyfiMUEmiGHNsZI7DmgUsvFTlODwIIux6_3NT-dkNkQRIR0aVM5UtoQN-M&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2248",
        productName: "Chowemin 4",
        subCategoryId: "Catering",
        vendorId: "1117",
        productPrice: "22",
        productRating: "4",
        productDescription: "Catering flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHJxJQ1-eMNrrWpINfzq0NQdwCJGkBNztEERrGUS0i_-r0GUWFvihmiT0gRYn6rotDTsA&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
    ],
  },
  {
    vendorId: "1118",
    vendorName: "Taste of India",
    businessName: "Taste of India Resturant",
    businessAddress: "Toronto",
    vendorProfileImage:
      "https://im.rediff.com/getahead/2015/mar/27chef-ranveer-brar-1.jpg",
    businessCoverImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY6aNvxfCqFbuZM-xY_oBLR9soQN9N0-lHkeaHsjCd2fJgMbS1CMINzcrhp6ANXfBOfpc&usqp=CAU",
    phoneNumber: 9876541118,
    zipcode: 80118,
    emailId: "TasteofIndia@gmail.com",
    vendorRating: 4,
    numberOfOrderedPlaced:56,
    subCategoryId: "East Indian",
    dietry: "Non Veg",
    tag: "Trending",
    foodSafetyCertified: "Yes",
    reviews: "74",
    subCategoryId: "Fried Chicken",
    product: [
      {
        productId: "2252",
        productName: "Dosa 2",
        subCategoryId: "Bengali",
        vendorId: "1118",
        productPrice: "11",
        productRating: "2",
        productDescription: "Bengali flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQBTfkBFeZFZGSzbZxmtmDz2kNi6vHFmtEhwUo6y1Ew4TS-5Sb0FS8B_9HWRK_Ys5HH6U&usqp=CAU",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2249",
        productName: "Saag 2",
        subCategoryId: "North Indian",
        vendorId: "1118",
        productPrice: "17",
        productRating: "2",
        productDescription: "North Indian flavored dish etc etc",
        productPhoto:
          "https://www.cookingcarnival.com/wp-content/uploads/2015/05/Rava-Dosa-2.jpg",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2250",
        productName: "Rabri 4",
        subCategoryId: "South Indian",
        vendorId: "1118",
        productPrice: "22",
        productRating: "2",
        productDescription: "South Indian flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmymuNkU0lPwQWdiRlw1AIYV09GUL-VsPp4A&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2251",
        productName: "Butter Chicken 2",
        subCategoryId: "Gujrati",
        vendorId: "1118",
        productPrice: "23",
        productRating: "5",
        productDescription: "Gujrati flavored dish etc etc",
        productSubDescription: "",
        productPhoto: "https://cafedelites.com/wp-content/uploads/2019/01/Butter-Chicken-IMAGE-64.jpg",
        isVeg: "true",
      },
    ],
  },
  {
    vendorId: "1119",
    vendorName: "Paratha Galli",
    businessName: "Paratha Galli Resturant",
    businessAddress: "Whitby",
    vendorProfileImage:
      "https://image.shutterstock.com/image-photo/cooking-profession-people-concept-happy-260nw-1307700994.jpg",
    businessCoverImage:
      "http://cdn.cnn.com/cnnnext/dam/assets/181031191840-01-india-ultimate-food-guide.jpg",
    phoneNumber: 9876541119,
    zipcode: 80119,
    emailId: "ParathaGalli@gmail.com",
    vendorRating: 4,
    numberOfOrderedPlaced:171,
    subCategoryId: "Chinese",
    dietry: "Non Veg",
    tag: "Highly Ordered",
    foodSafetyCertified: "No",
    reviews: "195",
    subCategoryId: "Indian Dish",
    product: [
      {
        productId: "2254",
        productName: "Mushroom Tikka 2",
        subCategoryId: "East Indian",
        vendorId: "1119",
        productPrice: "19",
        productRating: "5",
        productDescription: "East Indian flavored dish etc etc",
        productPhoto: "https://i.ytimg.com/vi/GTyw_LszfQM/maxresdefault.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2253",
        productName: "Veg Manchurian 1",
        subCategoryId: "West Indian",
        vendorId: "1119",
        productPrice: "23",
        productRating: "1",
        productDescription: "West Indian flavored dish etc etc",
        productPhoto:
          "https://myfoodstory.com/wp-content/uploads/2021/10/Veg-Manchurian-FI-1.jpg",
        productSubDescription: "",
        isVeg: "true",
      },
    ],
  },
  {
    vendorId: "1120",
    vendorName: "Best Bakery",
    businessName: "Best Bakery Resturant",
    businessAddress: "Brampton",
    vendorProfileImage:
      "https://www.deccanherald.com/sites/dh/files/article_images/2020/05/19/file7732s80ma824l2vd3em-319629494-1569267001.jpg",
    businessCoverImage:
      "https://assets.bonappetit.com/photos/5d7296eec4af4d0008ad1263/5:4/w_3165,h_2532,c_limit/Basically-Gojuchang-Chicken-Recipe-Wide.jpg",
    phoneNumber: 9876541120,
    zipcode: 80120,
    emailId: "BestBakery@gmail.com",
    vendorRating: 3,
    numberOfOrderedPlaced:169,
    subCategoryId: "Thali",
    dietry: "Vegan",
    tag: "Trending",
    foodSafetyCertified: "No",
    reviews: "158",
    subCategoryId: "Indian Dish",
    product: [
      {
        productId: "2255",
        productName: "Chowemin 4",
        subCategoryId: "Chinese",
        vendorId: "1120",
        productPrice: "12",
        productRating: "1",
        productDescription: "Chinese flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHJxJQ1-eMNrrWpINfzq0NQdwCJGkBNztEERrGUS0i_-r0GUWFvihmiT0gRYn6rotDTsA&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2257",
        productName: "Manchurian 3",
        subCategoryId: "Sweets",
        vendorId: "1120",
        productPrice: "16",
        productRating: "3",
        productDescription: "Sweets flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlATUM7ymtTIZ9jS2o16_M0_3dvvG_ozlMGl0s6MWuwJXZujdHtx3zkCXGZTqbpOALoxw&usqp=CAU",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2256",
        productName: "Rava Dosa 3",
        subCategoryId: "Batter",
        vendorId: "1120",
        productPrice: "18",
        productRating: "1",
        productDescription: "Batter flavored dish etc etc",
        productPhoto:
          "https://www.mydelicious-recipes.com/home/images/121_1200_1200/mydelicious-recipes-rava-dasa",
        productSubDescription: "",
        isVeg: "false",
      },
    ],
  },
  {
    vendorId: "1121",
    vendorName: "Just Sweets",
    businessName: "Just Sweets Resturant",
    businessAddress: "Kitchener",
    vendorProfileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9lijEs6OTztwYpPCme6l5glSwX23_Jm9JxLdOwmiRKF_Mnb1DaHT2EJ6Dbr0AJzbN2ks&usqp=CAU",
    businessCoverImage:
      "https://www.crazymasalafood.com/wp-content/images/masaledar-chicken-lollipop.png",
    phoneNumber: 9876541121,
    zipcode: 80121,
    emailId: "JustSweets@gmail.com",
    vendorRating: 5,
    numberOfOrderedPlaced:88,
    subCategoryId: "Dessert",
    dietry: "Non Veg",
    tag: "Newly Added",
    foodSafetyCertified: "No",
    reviews: "97",
    subCategoryId: "Indian Dish",
    product: [
      {
        productId: "2259",
        productName: "Rava Dosa 2",
        subCategoryId: "Dessert",
        vendorId: "1121",
        productPrice: "14",
        productRating: "2",
        productDescription: "Dessert flavored dish etc etc",
        productPhoto:
          "https://www.shettyscookery.com/wp-content/uploads/2021/07/rava-dosa10-1.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2260",
        productName: "Idli 5",
        subCategoryId: "Thali",
        vendorId: "1121",
        productPrice: "16",
        productRating: "3",
        productDescription: "Thali flavored dish etc etc",
        productPhoto:
          "https://www.livingsmartandhealthy.com/wp-content/uploads/2021/06/Quinoa-Idli_2.jpg",
        productSubDescription: "",
        isVeg: "false",
      },
      {
        productId: "2261",
        productName: "Matar Pulao 4",
        subCategoryId: "Catering",
        vendorId: "1121",
        productPrice: "12",
        productRating: "2",
        productDescription: "Catering flavored dish etc etc",
        productPhoto:
          "https://www.shikararestaurant.com/wp-content/uploads/2018/01/peace-pulao.jpg",
        productSubDescription: "",
        isVeg: "true",
      },
      {
        productId: "2258",
        productName: "Dhokla 3",
        subCategoryId: "Bakery",
        vendorId: "1121",
        productPrice: "14",
        productRating: "2",
        productDescription: "Bakery flavored dish etc etc",
        productPhoto:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ0BObINYHTvoL6URqjdY9RlL8Uh9W5_LRcShu24ruBOLO_ucrgPsxtUcp7kQ2X692K7c&usqp=CAU",
        productSubDescription: "",
        isVeg: "true",
      },
    ],
  },
];

// export const restaurantList = [
//     {
//       vendorId: "1112",
//       vendorName: "Sharma Ji",
//       businessName: "Sharma Ji Restaurant",
//       businessAddress: "2/D block, Tronto, Canada",
//       vendorProfileImage: "https://coox-new.s3.ap-south-1.amazonaws.com/images/cook/19420/profile-img516e5d36-64b3-4c4c-8cb2-d1fa28dbc317.jpeg?v=1636799907226",
//       businessCoverImage: "https://sukhis.com/app/uploads/2018/10/ex2.jpg",
//       phoneNumber: 982135432,
//       zipcode: 412541,
//       emailId: "sharmaji@gmail.com",
//       vendorRating: 4.5,
//       numberOfOrderedPlaced: 350,
//       subCategoryId: "North Indian",
//       subCategoryId: "Fast food",
//       product: [
//         {
//           productId: "2223",
//           productName: "Dosa",
//           subCategoryId: "North Indian",
//           vendorId: "1112",
//           productPrice: "125",
//           productRating: "2.5",
//           productDescription: "Indian Dosa good in taste and quality",
//           productPhoto: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
//           productSubDescription: "Medium size dosa",
//           isVeg: false,

//         },
//         {
//           productId: "2224",
//           productName: "Burger",
//           subCategoryId: "Snacks",
//           vendorId: "1112",
//           productPrice: "120",
//           productRating: "4.5",
//           productDescription: "Indian burger good in taste and quality",
//           productPhoto: "https://www.thespruceeats.com/thmb/ad4-cZdHW0fHWDn_JSuh3FTjLag=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/garlic-burger-patties-333503-hero-01-e4df660ff27b4e5194fdff6d703a4f83.jpg",
//           productSubDescription: "Medium size burger",
//           isVeg: false,
//         },
//         {
//           productId: "2225",
//           productName: "Samosa",
//           subCategoryId: "fast food",
//           vendorId: "1112",
//           productPrice: "50",
//           productRating: "3.5",
//           productDescription: "Indian Fast Food  good in taste and quality",
//           productPhoto: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Samosachutney.jpg",
//           productSubDescription: "large size samosa",
//           isVeg: false,
//         },
//       ],
//     },
//     {
//       vendorId: "1113",
//       vendorName: "Pandya Ji",
//       businessName: "Pandya Restaurant",
//       businessAddress: "2/D block, Tronto, Canada",
//       vendorProfileImage: "https://coox-new.s3.ap-south-1.amazonaws.com/images/cook/19420/profile-img516e5d36-64b3-4c4c-8cb2-d1fa28dbc317.jpeg?v=1636799907226",
//       businessCoverImage: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
//       phoneNumber: 982135432,
//       zipcode: 412541,
//       emailId: "Pandya@gmail.com",
//       vendorRating: 3,
//       numberOfOrderedPlaced: 250,
//       subCategoryId: "South food",
//       product: [
//         {
//           productId: "3223",
//           productName: "idli",
//           subCategoryId: "South Indian",
//           vendorId: "1113",
//           productPrice: "125",
//           productRating: "4.5",
//           productDescription: "Indian Idli",
//           productPhoto: "https://shwetainthekitchen.com/wp-content/uploads/2022/01/Idli.jpg",
//           productSubDescription: "Medium size idli",
//           isVeg: false,

//         },
//         {
//           productId: "3224",
//           productName: "burger",
//           subCategoryId: "Snacks",
//           vendorId: "1113",
//           productPrice: "100",
//           productRating: "2.5",
//           productDescription: "Indian burger",
//           productPhoto: "https://www.seriouseats.com/thmb/vOsRuVEH7ZhQVOVVP42VJ-eu4Rg=/880x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/20210607-INNOUTBURGERS-JANJIGIAN-seriouseats-23-b2b8a505ff414272aab71590a8985b85.jpg",
//           productSubDescription: "Medium size burger",
//           isVeg: true,
//         },
//         {
//           productId: "3225",
//           productName: "samosa",
//           subCategoryId: "fast food",
//           vendorId: "1113",
//           productPrice: "53",
//           productRating: "4.5",
//           productDescription: "Indian Fast Food",
//           productPhoto: "https://sukhis.com/app/uploads/2018/10/ex2.jpg",
//           productSubDescription: "large size samosa",
//           isVeg: true,
//         },
//       ],
//     },
//     {
//       vendorId: "1114",
//       vendorName: "Mishra Ji",
//       businessName: "Mishra Restaurant",
//       businessAddress: "2/D block, Tronto, Canada",
//       vendorProfileImage: "https://coox-new.s3.ap-south-1.amazonaws.com/images/cook/19420/profile-img516e5d36-64b3-4c4c-8cb2-d1fa28dbc317.jpeg?v=1636799907226",
//       businessCoverImage: "https://shwetainthekitchen.com/wp-content/uploads/2022/01/Idli.jpg",
//       phoneNumber: 982135432,
//       zipcode: 456123,
//       emailId: "MishraJi@gmail.com",
//       vendorRating: 2.5,
//       numberOfOrderedPlaced: 250,
//       subCategoryId: "South Indian",
//       product: [
//         {
//           productId: "4223",
//           productName: "idli",
//           subCategoryId: "South Indian",
//           vendorId: "1114",
//           productPrice: "115",
//           productRating: "2.5",
//           productDescription: "Indian Idli",
//           productPhoto: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/idli.jpg.webp",
//           productSubDescription: "Medium size idli",
//           isVeg: false,
//         },
//         {
//           productId: "4224",
//           productName: "burger",
//           subCategoryId: "Snacks",
//           vendorId: "1114",
//           productPrice: "100",
//           productRating: "2.5",
//           productDescription: "Indian burger",
//           productPhoto: "https://assets.epicurious.com/photos/5c745a108918ee7ab68daf79/1:1/w_1920,c_limit/Smashburger-recipe-120219.jpg",
//           productSubDescription: "Medium size burger",
//           isVeg: false,
//         },
//         {
//           productId: "4225",
//           productName: "samosa",
//           subCategoryId: "fast food",
//           vendorId: "1114",
//           productPrice: "42",
//           productRating: "4.5",
//           productDescription: "Indian Fast Food",
//           productPhoto: "https://i0.wp.com/vegecravings.com/wp-content/uploads/2017/03/samosa-recipe-step-by-step-instructions.jpg?resize=1024%2C976&quality=65&strip=all&ssl=1",
//           productSubDescription: "large size samosa",
//           isVeg: false,
//         },
//       ],
//     },
//     {
//       vendorId: "1115",
//       vendorName: "ratan Sharma",
//       vendorProfileImage: "https://coox-new.s3.ap-south-1.amazonaws.com/images/cook/19420/profile-img516e5d36-64b3-4c4c-8cb2-d1fa28dbc317.jpeg?v=1636799907226",
//       businessName: "Food Lover",
//       businessAddress: "2/D block, Tronto, Canada",
//       businessCoverImage: "https://www.thespruceeats.com/thmb/ad4-cZdHW0fHWDn_JSuh3FTjLag=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/garlic-burger-patties-333503-hero-01-e4df660ff27b4e5194fdff6d703a4f83.jpg",
//       phoneNumber: 982135432,
//       zipcode: 412333,
//       emailId: "foodlover@gmail.com",
//       vendorRating: 3.5,
//       numberOfOrderedPlaced: 250,
//       subCategoryId: "Fast food",
//       product:[],
//     },
//     {
//       vendorId: "1116",
//       vendorName: "Roy Ji",
//       businessAddress: "2/D block, Tronto, Canada",
//       businessName: "Fresh Food Restaurant",
//       vendorProfileImage: "https://coox-new.s3.ap-south-1.amazonaws.com/images/cook/19420/profile-img516e5d36-64b3-4c4c-8cb2-d1fa28dbc317.jpeg?v=1636799907226",
//       businessCoverImage: "https://lh3.googleusercontent.com/eDknPUTcea-07etrh_INv8LV5Zp97McLtu97JUkFaHB-Y6LsC7FACPXaz7lISt02WGNQ4dlQiwjHOOIVwxdyVgiiqol9lcEYZHBNJow",
//       phoneNumber: 9821585432,
//       zipcode: 410541,
//       emailId: "freshFood@gmail.com",
//       vendorRating: 4.3,
//       numberOfOrderedPlaced: 750,
//       subCategoryId: "Regular Thali",
//       product:[],
//     },
//     {
//       vendorId: "1117",
//       vendorName: "Spicy",
//       businessAddress: "2/D block, Tronto, Canada",
//       vendorProfileImage: "https://coox-new.s3.ap-south-1.amazonaws.com/images/cook/19420/profile-img516e5d36-64b3-4c4c-8cb2-d1fa28dbc317.jpeg?v=1636799907226",
//       businessName: "Spicy Restaurant",
//       businessCoverImage: "https://www.simplyrecipes.com/thmb/YR4CZyRSLKCFCLkU50UEfgpkG9w=/648x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__06__Spicy-Fried-Chicken-LEAD-3-24b25010ba0c4737b5fa5957f8f22d0e.jpg",
//       phoneNumber: 9821585432,
//       zipcode: 410641,
//       emailId: "Spicy@gmail.com",
//       vendorRating: 4.1,
//       numberOfOrderedPlaced: 50,
//       subCategoryId: "Spicy Chicken",
//       product:[],
//     },
//     {
//       vendorId: "1117",
//       vendorName: "Saurab Roy",
//       businessAddress: "2/D block, Tronto, Canada",
//       businessName: "AFC",
//       vendorProfileImage: "https://coox-new.s3.ap-south-1.amazonaws.com/images/cook/19420/profile-img516e5d36-64b3-4c4c-8cb2-d1fa28dbc317.jpeg?v=1636799907226",
//       businessCoverImage: "https://afc.world/wp-content/uploads/2021/10/AFC-Bucket-Mob.png",
//       phoneNumber: 9821585432,
//       zipcode: 410541,
//       emailId: "saurabroy@gmail.com",
//       vendorRating: 4.3,
//       numberOfOrderedPlaced: 450,
//       subCategoryId: "Fried Chicken",
//       product:[],
//     },
//     {
//       vendorId: "1118",
//       vendorName: "Rohit Roy",
//       businessAddress: "2/D block, Tronto, Canada",
//       businessName: "Tuli's Restaurant",
//       businessCoverImage: "https://www.nehascookbook.com/wp-content/uploads/2021/08/Punjabi-thali-WS.jpg",
//       phoneNumber: 9821585432,
//       zipcode: 410541,
//       emailId: "tulis@gmail.com",
//       vendorRating: 4.3,
//       numberOfOrderedPlaced: 450,
//       subCategoryId: "Indian Dish",
//       product:[],
//     },
//   ];
